id: P000448
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20768
  title: 'མཁས་འཇུག་གི་མཆན་འགྲེལ་ལེགས་བཤད་སྣང་བའི་འོད་ཟེར་རལ་གྲི་དང་ཨུཏྤལའི་སྐོར། '
  author: ''
  volumes:
    59809ca1589842d2b08cd61b090cffe0:
      image_group_id: I8LS20831
      title: Volume 1 of mkhas 'jug gi mchan 'grel legs bshad snang ba'i 'od zer ral
        gri dang uta+pala'i skor/
      volume_number: 1
      total_pages: 516
      base_file: v001.txt
